export enum IconKey {
  Star = 'star',
  Sun = 'sun',
  Moon = 'moon',
  Coffee = 'coffee',
  Book = 'book',
  Dumbbell = 'dumbbell',
  Meditation = 'meditation',
  Music = 'music',
  Heart = 'heart',
  CheckCircle = 'check-circle',
  Running = 'running',
  Sleep = 'sleep',
  Breakfast = 'breakfast',
  Shower = 'shower',
  Reading = 'reading',
  Writing = 'writing',
  Work = 'work',
  Study = 'study'
}